package jp.ne.sakura.sync.web.mepper;

import java.util.List;
import jp.ne.sakura.sync.web.entity.PositionInfo;
import jp.ne.sakura.sync.web.entity.PositionInfoExample;
import org.apache.ibatis.annotations.Param;

public interface PositionInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_info
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    long countByExample(PositionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_info
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    int deleteByExample(PositionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_info
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    int insert(PositionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_info
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    int insertSelective(PositionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_info
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    List<PositionInfo> selectByExample(PositionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_info
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    int updateByExampleSelective(@Param("record") PositionInfo record, @Param("example") PositionInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_info
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    int updateByExample(@Param("record") PositionInfo record, @Param("example") PositionInfoExample example);
}