package jp.ne.sakura.sync.web.entity;

import java.util.Date;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.name
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.mail
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.position_no
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    private Integer positionNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.insert_dt
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    private Date insertDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.update_dt
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    private Date updateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.name
     *
     * @return the value of employee.name
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.name
     *
     * @param name the value for employee.name
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.mail
     *
     * @return the value of employee.mail
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.mail
     *
     * @param mail the value for employee.mail
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.position_no
     *
     * @return the value of employee.position_no
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public Integer getPositionNo() {
        return positionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.position_no
     *
     * @param positionNo the value for employee.position_no
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public void setPositionNo(Integer positionNo) {
        this.positionNo = positionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.insert_dt
     *
     * @return the value of employee.insert_dt
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public Date getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.insert_dt
     *
     * @param insertDt the value for employee.insert_dt
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public void setInsertDt(Date insertDt) {
        this.insertDt = insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.update_dt
     *
     * @return the value of employee.update_dt
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public Date getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.update_dt
     *
     * @param updateDt the value for employee.update_dt
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public void setUpdateDt(Date updateDt) {
        this.updateDt = updateDt;
    }
}