package jp.ne.sakura.sync.web.entity;

import java.util.Date;

public class Login {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.id
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.name
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.password
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.insert_dt
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    private Date insertDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.update_dt
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    private Date updateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.id
     *
     * @return the value of login.id
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.id
     *
     * @param id the value for login.id
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.name
     *
     * @return the value of login.name
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.name
     *
     * @param name the value for login.name
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.password
     *
     * @return the value of login.password
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.password
     *
     * @param password the value for login.password
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.insert_dt
     *
     * @return the value of login.insert_dt
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public Date getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.insert_dt
     *
     * @param insertDt the value for login.insert_dt
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public void setInsertDt(Date insertDt) {
        this.insertDt = insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.update_dt
     *
     * @return the value of login.update_dt
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public Date getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.update_dt
     *
     * @param updateDt the value for login.update_dt
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public void setUpdateDt(Date updateDt) {
        this.updateDt = updateDt;
    }
}