package jp.ne.sakura.sync.web.entity;

import java.util.Date;

public class PositionInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position_info.id
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position_info.position_name
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    private String positionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position_info.insert_dt
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    private Date insertDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position_info.update_dt
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    private Date updateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position_info.id
     *
     * @return the value of position_info.id
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position_info.id
     *
     * @param id the value for position_info.id
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position_info.position_name
     *
     * @return the value of position_info.position_name
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position_info.position_name
     *
     * @param positionName the value for position_info.position_name
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position_info.insert_dt
     *
     * @return the value of position_info.insert_dt
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public Date getInsertDt() {
        return insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position_info.insert_dt
     *
     * @param insertDt the value for position_info.insert_dt
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public void setInsertDt(Date insertDt) {
        this.insertDt = insertDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position_info.update_dt
     *
     * @return the value of position_info.update_dt
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public Date getUpdateDt() {
        return updateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position_info.update_dt
     *
     * @param updateDt the value for position_info.update_dt
     *
     * @mbg.generated Tue Mar 13 14:45:42 JST 2018
     */
    public void setUpdateDt(Date updateDt) {
        this.updateDt = updateDt;
    }
}